# wrangler.toml
name = "eson" # 必填，Worker 名称（建议与项目名一致）
main = "_worker.js"     # 必填，入口文件路径（若你的入口是 _worker.js，改为 "_worker.js"）
compatibility_date = "2025-06-12" # 可选，指定 Workers 运行时版本

# 构建配置（如果需要编译代码，如 TypeScript/JavaScript）
[build]
# command = "npm run build" # 构建命令（如使用框架需开启）
# directory = "dist"        # 构建输出目录
# minify = true             # 是否压缩代码

# 环境变量（可选，用于配置敏感信息或动态参数）
[env.development]
# KEY = "value"

[env.production]
# KEY = "value"

# 路由规则（可选，配置自定义路由）
# [[route]]
# pattern = "example.com/*"
# script = "your-worker-name"
